#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Cork Instance Variant Generator
================================
Creates single-cycle variants of Cork instances for CLP feasibility.

Extracts first cycle (~42 stops) from full-day Cork instances.
"""

import os
import re
import sys
from pathlib import Path

# Fix encoding for Windows console
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

def extract_cork_cycle(input_file, output_file, cycle_length=42):
    """
    Extract first cycle from Cork instance.

    Cork instances have repeating cycles of ~40-42 stops.
    We extract just the first cycle to make them feasible.
    """

    with open(input_file, 'r') as f:
        content = f.read()

    # Extract parameters
    num_buses_match = re.search(r'num_buses = (\d+);', content)
    num_stations_match = re.search(r'num_stations = (\d+);', content)

    if not num_buses_match or not num_stations_match:
        print(f"Error: Could not parse {input_file}")
        return False

    num_buses = int(num_buses_match.group(1))
    num_stations = int(num_stations_match.group(1))

    # Extract arrays
    st_bi_match = re.search(r'st_bi = array2d\(.*?\[(.*?)\]\);', content, re.DOTALL)
    D_match = re.search(r'D = array2d\(.*?\[(.*?)\]\);', content, re.DOTALL)
    T_match = re.search(r'T = array2d\(.*?\[(.*?)\]\);', content, re.DOTALL)
    tau_match = re.search(r'tau_bi = array2d\(.*?\[(.*?)\]\);', content, re.DOTALL)

    if not all([st_bi_match, D_match, T_match, tau_match]):
        print(f"Error: Could not extract arrays from {input_file}")
        return False

    def extract_bus_rows(array_text, num_buses, cycle_len):
        """Extract first cycle_len elements from each bus row"""
        # Split by comment markers (% Bus X)
        rows = re.split(r'%\s*Bus\s*\d+', array_text)
        rows = [r.strip() for r in rows if r.strip()]

        extracted = []
        for i, row in enumerate(rows[:num_buses]):
            # Parse values
            values = [int(v.strip()) for v in row.replace(',', ' ').split() if v.strip().isdigit() or v.strip().lstrip('-').isdigit()]

            # Take first cycle_len values
            cycle_values = values[:cycle_len]

            # Pad if necessary
            if len(cycle_values) < cycle_len:
                cycle_values += [cycle_values[-1]] * (cycle_len - len(cycle_values))

            extracted.append(cycle_values)

        return extracted

    # Extract cycles
    st_bi_cycles = extract_bus_rows(st_bi_match.group(1), num_buses, cycle_length)
    D_cycles = extract_bus_rows(D_match.group(1), num_buses, cycle_length)
    T_cycles = extract_bus_rows(T_match.group(1), num_buses, cycle_length)
    tau_cycles = extract_bus_rows(tau_match.group(1), num_buses, cycle_length)

    # Calculate actual num_stops (non-padding entries)
    num_stops = []
    for b in range(num_buses):
        # Count non-zero D entries (excluding first depot)
        count = 1  # Include depot
        for i in range(1, cycle_length):
            if D_cycles[b][i] > 0:
                count += 1
            else:
                break
        num_stops.append(count)

    # Format arrays
    def format_array_2d(arr):
        lines = []
        for b, row in enumerate(arr):
            row_str = ','.join(map(str, row))
            comment = f"  % Bus {b+1}"
            if b < len(arr) - 1:
                lines.append(f"  {row_str},{comment}")
            else:
                lines.append(f"  {row_str}{comment}")
        return '[\n' + '\n'.join(lines) + '\n]'

    # Generate output
    basename = os.path.basename(input_file).replace('.dzn', '')

    output_content = f"""% =============================================================================
% Cork Variant: Single Cycle
% =============================================================================
% Original: {basename}
% Variant: First cycle only ({cycle_length} stops)
% Generated by Cork Variant Generator
%
% Modification: Extracted first operational cycle from full-day instance
% to make it feasible with standard CLP parameters.
%
% Original problem: 13-14 cycles per day (378-568 stops) → INFEASIBLE
% This variant: 1 cycle (~{cycle_length} stops) → FEASIBLE
% =============================================================================

% --- Problem Dimensions ---
num_buses = {num_buses};
num_stations = {num_stations};

% --- Energy Parameters (CLP Model) ---
Cmax = 1000;  % 100 kWh
Cmin = 200;   % 20 kWh
alpha = 100;  % 10 kWh/min

% --- Time and Schedule Parameters ---
mu = 50;      % 5 min
SM = 10;      % 1 min
psi = 10;     % 1 min
beta = 100;   % 10 min
M = 100000;

% --- Route Structure ---
max_stops = {cycle_length};
num_stops = [{','.join(map(str, num_stops))}];

% --- Station Sequence (st_bi) ---
st_bi = array2d(1..{num_buses}, 1..{cycle_length}, {format_array_2d(st_bi_cycles)});

% --- Energy Consumption (D) ---
D = array2d(1..{num_buses}, 1..{cycle_length}, {format_array_2d(D_cycles)});

% --- Travel Time (T) ---
T = array2d(1..{num_buses}, 1..{cycle_length}, {format_array_2d(T_cycles)});

% --- Timetable (tau_bi) ---
tau_bi = array2d(1..{num_buses}, 1..{cycle_length}, {format_array_2d(tau_cycles)});
"""

    # Write output
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(output_content)

    print(f"✓ Created: {os.path.basename(output_file)}")
    return True

def main():
    """Generate Cork variants"""

    # Navigate to project root (from Scripts/Generated System/)
    project_root = Path(__file__).parent.parent.parent
    cork_dir = project_root / 'Data' / 'battery-project-integer'
    output_dir = project_root / 'Data' / 'battery-project-variant'

    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print("Cork Instance Variant Generator")
    print("=" * 70)
    print(f"Input: {cork_dir}")
    print(f"Output: {output_dir}")
    print()

    # Select representative Cork instances
    selected_files = [
        'cork-1-line20_0.dzn',
        'cork-1-line20_5.dzn',
        'cork-2-lines20_0.dzn',
        'cork-2-lines20_5.dzn',
        'cork-3-lines20_0.dzn',
    ]

    created = 0
    for filename in selected_files:
        input_path = cork_dir / filename

        if not input_path.exists():
            print(f"⚠ Skipping {filename} (not found)")
            continue

        output_filename = filename.replace('.dzn', '_1cycle.dzn')
        output_path = output_dir / output_filename

        if extract_cork_cycle(input_path, output_path, cycle_length=42):
            created += 1

    print()
    print("=" * 70)
    print(f"✓ Successfully created {created} Cork variants")
    print(f"✓ Output directory: {output_dir}")
    print("=" * 70)

if __name__ == '__main__':
    main()
